#%RAML 1.0 DataType
type: object
properties:
  
  id: integer
  applicantName: string
  dateOfApplication: string
  jobId: integer
  applicantType: string
  applicationStatus: string
  onlineTestStatus: string
  onlineTestEvaluation: string
  score: number
  locationPreference1: string
  locationPreference2: string
  locationPreference3: string
  contactNumber: number
  emailId: string
  currentLocation: string
  qualification: string
  collegeName: string
  passoutYear: number
  programmingSkills: string
  experience: integer
  designation: string
  expInCC: string
  noticePeriod: string
  openForRelocation: string
  currentSalary: number
  expectedSalary: number
  currentRound: string
  interviewPanelist: string
  comments: string
  