#%RAML 1.0 Library
usage:

traits:
  # crteAcc_qryParams: !include /QueryParams/crteAcc_queryParams_trait.raml
  chckBlnece_qryPrms: !include /QueryParams/checkBlnce_qryPrms_trait.raml
  # wthdrw_qryPrms: !include /QueryParams/withdraw_qryPrms_example.raml