#%RAML 1.0 NamedExample
{
  "CustomerID": "ABC123",
  "CustomerFirstName": "Thirupathi",
  "CustomerMiddleName": "Raj",
  "CustomerLastName": "B",
  "Address": {
                "StreetName": "AravindNagar",
                "Zipcode": "505327",
                "State": "Telangana",
                "Country": "INDIA"
               },
}