#%RAML 1.0
title: custom-policy

/employees:
  get:
   responses:
     200:
       body:
         application/json:
           example:
             {
               "name": "thiru",
               "id": "111"
             }