#%RAML 1.0 Trait
queryParameters:
  UserID1:
    required: false
    example: '11'
    type: string
    minLength: 1
    maxLength: 4
  UserID2:
    required: false
    example: '12'
    type: string 
  UserID3:
    required: false
    example: '13'
    type: string 