#%RAML 1.0 Trait
headers:
  applicantName:
    type: string
    required: true
  contactNumber:
    type: string
    required: true
  emailId:
    type: string
    required: true
  currentLocation:
    type: string
    required: true
  qualification:
    type: string
    required: true
  collegeName:
    type: string
    required: true
  programmingSkills:
    type: string
    required: true
  expInCC:
    type: string
    required: true
  currentSalary:
    type: string
    required: true
  expectedSalary:
    type: string
    required: true