#%RAML 1.0 DataType
type: object
properties:
  applicantName:
    type: string
    required: true
    example: "Thirupathi"
  contactNumber:
    type: string
    required: true
    example: "8790120632"
  emailId:
    type: string
    required: true
    example: "thirupathiraj2018@gmail.com"
  currentLocation:
    type: string
    required: true
    example: "Hyderabad"
  qualification:
    type: string
    required: true
    example: "BTech"
  collegeName:
    type: string
    required: true
    example: "JNTUH"
  programmingSkills:
    displayName: "write skills with comma separated"
    type: string
    required: true
    example:  "Java, Python, Mulesoft"
  expInCC:
    type: string
    required: true
    example: "Senior"
  currentSalary:
    type: string
    required: true
    example: "4LPA"
  expectedSalary:
    type: string
    required: true
    example: "7LPA"

    
  # id: integer
  # applicantName: string
  # dateOfApplication: string
  # jobId: integer
  # applicantType: string
  # applicationStatus: string
  # onlineTestStatus: string
  # onlineTestEvaluation: string
  # score: number
  # locationPreference1: string
  # locationPreference2: string
  # locationPreference3: string
  # contactNumber: number
  # emailId: string
  # currentLocation: string
  # qualification: string
  # collegeName: string
  # passoutYear: number
  # programmingSkills: string
  # experience: integer
  # designation: string
  # expInCC: string
  # noticePeriod: string
  # openForRelocation: string
  # currentSalary: number
  # expectedSalary: number
  # currentRound: string
  # interviewPanelist: string
  # comments: string
  