#%RAML 1.0 DataType
type: object
properties:
  applicantName:
    type: string
    required: true
    example: "Thirupathi"
  contactNumber:
    type: string
    required: true
    example: "8790120632"
  emailId:
    type: string
    required: true
    example: "thirupathiraj2018@gmail.com"
  currentLocation:
    type: string
    required: true
    example: "Hyderabad"
  qualification:
    type: string
    required: true
    example: "BTech"
  collegeName:
    type: string
    required: true
    example: "JNTUH"
  programmingSkills:
    displayName: "write skills with comma separated"
    type: string
    required: true
    example:  "Java, Python, Mulesoft"
  expInCC:
    type: string
    required: true
    example: "Senior"
  currentSalary:
    type: string
    required: true
    example: "4LPA"
  expectedSalary:
    type: string
    required: true
    example: "7LPA"
  applicantType:
    enum: ['Fresher', 'Experienced']
    required: true
    example: "Fresher"
  locationPreference1:
    enum: ["Hyderabad", "Bangalore", "Pune"]
    required: true
    example: "Hyderabad"
  locationPreference2:
    enum: ["Hyderabad", "Bangalore", "Pune"]
    required: true
    example: "Bangalore"
  locationPreference3:
    enum: ["Hyderabad", "Bangalore", "Pune"]
    required: true
    example: "Pune"
  passoutYear:
    enum: ["2022", "2021", "2020", "2019"]
    required: true
    example: "2019"
  experienceInYears:
    enum: ["0", "1", "2", "3"]
    required: true
    example: "2"
  noticePeriodInMonths:
    enum: ["0", "1", "2", "3"]
    required: true
    example: "2"
  openForRelocation:
    enum: ['Yes', 'No']
    required: true
    example: "Yes"