[
    {
        "DATEOFJOINING": "04-10-2021",
        "DEPTID": "11DEPTID",
        "DESIGNATION": "Sr_Analyst",
        "SALARY": "40k",
        "USERID": "11",
        "FIRSTNAME": "Thiru1",
        "PHONE": "8790120632",
        "ADDRESS1": "1-5",
        "MIDDLENAME": "B",
        "LASTNAME": "Bommishetty"
    }
  ]