#%RAML 1.0 DataType
type: array
items: 
  type: object
  properties:
    DATEOFJOINING:
      type: string
      required: true
      example: "04-10-2021"
    DEPTID:   
      type: string
      required: true
      example: "11DEPTID"
    DESIGNATION:
      type: string
      required: true
      example: "Sr_Analyst"
    SALARY: 
      type: string
      required: true
      example: "40k"
    USERID: 
      type: string
      required: true
      example: "11"
    FIRSTNAME: 
      type: string
      required: true
      example: "Thiru1"
    PHONE: 
      type: string
      required: true
      example: "8790120632"
    ADDRESS1: 
      type: string
      required: true
      example: "1-5"
    MIDDLENAME:   
      type: string
      required: true
      example: "B"
    LASTNAME: 
      type: string
      required: true
      example: "Bommishetty"
      
      
      